FROM python:3.12-slim

# uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app
COPY . .

# installe toutes les dépendances depuis le uv.lock
RUN uv sync --frozen --extra postgres

EXPOSE 8501

CMD ["uv", "run", "streamlit", "run", "streamlit/streamlit_app.py", "--server.address=0.0.0.0"]
